/**
 ** Name: Styles of App
 ** Author: Jerry
 ** CreateAt: 2021
 ** Description: Description of styles.js
 **/
// import {isIphoneX} from 'react-native-iphone-x-helper';
import {Platform, Dimensions} from 'react-native';
/** COMMON */
import {IS_IOS, moderateScale} from '~/utils/helper';
import Colors from './Colors';

const PLATFORM = {
  ANDROID: 'android',
  IOS: 'ios',
};
export const FONTS = {
  light: 'Poppins-Light',
  regular: 'Poppins-Regular',
  medium: 'Poppins-Medium',
  bold: 'Poppins-SemiBold',
};

const deviceHeight = Dimensions.get('window').height;
const deviceWidth = Dimensions.get('window').width;
const platform = Platform.OS;
const toolbarHeight = platform === PLATFORM.IOS ? 52 : 56;
const toolbarHeight1 = 88;
const toolbarDefaultBorder = Colors.PRIMARY;


const main = {
  flex1: {flex: 1},
  flexWrap: {flexWrap: 'wrap'},
  flexNoWrap: {flexWrap: 'nowrap'},
  flexGrow: {flexGrow: 1},
  flexWrapReverse: {flexWrap: 'wrap-reverse'},
  row: {flexDirection: 'row'},
  col: {flexDirection: 'column'},
  flexCenter: {flex: 1, alignItems: 'center', justifyContent: 'center'},
  center: {alignItems: 'center', justifyContent: 'center'},
  itemsStretch: {alignItems: 'stretch'},
  itemsBaseline: {alignItems: 'baseline'},
  itemsStart: {alignItems: 'flex-start'},
  itemsEnd: {alignItems: 'flex-end'},
  itemsCenter: {alignItems: 'center'},
  justifyBetween: {justifyContent: 'space-between'},
  justifyAround: {justifyContent: 'space-around'},
  justifyEvenly: {justifyContent: 'space-evenly'},
  justifyStart: {justifyContent: 'flex-start'},
  justifyEnd: {justifyContent: 'flex-end'},
  justifyCenter: {justifyContent: 'center'},
  fullWidth: {width: '100%'},
  fullHeight: {height: '100%'},
  platform,
  // isIphoneX,
  toolbarHeight,
  toolbarHeight1,
  toolbarDefaultBorder,
  deviceHeight,
  deviceWidth,
  ofHidden: {overflow: 'hidden'},
  ofScroll: {overflow: 'scroll'},
  ofVisible: {overflow: 'visible'},
  aliSelCenter: {alignSelf: 'center'},
  displayFlex: {display: 'flex'},
};

const padding = {
  pl0: {paddingLeft: 0},
  pl1: {paddingLeft: moderateScale(1)},
  pl2: {paddingLeft: moderateScale(2)},
  pl3: {paddingLeft: moderateScale(3)},
  pl4: {paddingLeft: moderateScale(4)},
  pl5: {paddingLeft: moderateScale(5)},
  pl6: {paddingLeft: moderateScale(6)},
  pl8: {paddingLeft: moderateScale(8)},
  pl10: {paddingLeft: moderateScale(10)},
  pl12: {paddingLeft: moderateScale(12)},
  pl16: {paddingLeft: moderateScale(16)},
  pl20: {paddingLeft: moderateScale(20)},
  pl24: {paddingLeft: moderateScale(24)},
  pl28: {paddingLeft: moderateScale(28)},
  pl32: {paddingLeft: moderateScale(32)},
  pl36: {paddingLeft: moderateScale(36)},
  pl40: {paddingLeft: moderateScale(40)},
  pl44: {paddingLeft: moderateScale(44)},
  pl48: {paddingLeft: moderateScale(48)},
  pl52: {paddingLeft: moderateScale(52)},
  pl56: {paddingLeft: moderateScale(56)},
  pl60: {paddingLeft: moderateScale(60)},

  pr0: {paddingRight: 0},
  pr1: {paddingRight: moderateScale(1)},
  pr2: {paddingRight: moderateScale(2)},
  pr3: {paddingRight: moderateScale(3)},
  pr4: {paddingRight: moderateScale(4)},
  pr5: {paddingRight: moderateScale(5)},
  pr6: {paddingRight: moderateScale(6)},
  pr8: {paddingRight: moderateScale(8)},
  pr10: {paddingRight: moderateScale(10)},
  pr12: {paddingRight: moderateScale(12)},
  pr16: {paddingRight: moderateScale(16)},
  pr20: {paddingRight: moderateScale(20)},
  pr24: {paddingRight: moderateScale(24)},
  pr28: {paddingRight: moderateScale(28)},
  pr32: {paddingRight: moderateScale(32)},
  pr36: {paddingRight: moderateScale(36)},
  pr40: {paddingRight: moderateScale(40)},
  pr44: {paddingRight: moderateScale(44)},
  pr48: {paddingRight: moderateScale(48)},
  pr52: {paddingRight: moderateScale(52)},
  pr56: {paddingRight: moderateScale(56)},
  pr60: {paddingRight: moderateScale(60)},

  pt0: {paddingTop: 0},
  pt1: {paddingTop: moderateScale(1)},
  pt2: {paddingTop: moderateScale(2)},
  pt3: {paddingTop: moderateScale(3)},
  pt4: {paddingTop: moderateScale(4)},
  pt5: {paddingTop: moderateScale(5)},
  pt6: {paddingTop: moderateScale(6)},
  pt8: {paddingTop: moderateScale(8)},
  pt10: {paddingTop: moderateScale(10)},
  pt12: {paddingTop: moderateScale(12)},
  pt16: {paddingTop: moderateScale(16)},
  pt20: {paddingTop: moderateScale(20)},
  pt24: {paddingTop: moderateScale(24)},
  pt28: {paddingTop: moderateScale(28)},
  pt32: {paddingTop: moderateScale(32)},
  pt36: {paddingTop: moderateScale(36)},
  pt40: {paddingTop: moderateScale(40)},
  pt44: {paddingTop: moderateScale(44)},
  pt48: {paddingTop: moderateScale(48)},
  pt52: {paddingTop: moderateScale(52)},
  pt56: {paddingTop: moderateScale(56)},
  pt60: {paddingTop: moderateScale(60)},

  pb0: {paddingBottom: 0},
  pb1: {paddingBottom: moderateScale(1)},
  pb2: {paddingBottom: moderateScale(2)},
  pb3: {paddingBottom: moderateScale(3)},
  pb4: {paddingBottom: moderateScale(4)},
  pb5: {paddingBottom: moderateScale(5)},
  pb6: {paddingBottom: moderateScale(6)},
  pb8: {paddingBottom: moderateScale(8)},
  pb10: {paddingBottom: moderateScale(10)},
  pb12: {paddingBottom: moderateScale(12)},
  pb16: {paddingBottom: moderateScale(16)},
  pb20: {paddingBottom: moderateScale(20)},
  pb24: {paddingBottom: moderateScale(24)},
  pb28: {paddingBottom: moderateScale(28)},
  pb32: {paddingBottom: moderateScale(32)},
  pb36: {paddingBottom: moderateScale(36)},
  pb40: {paddingBottom: moderateScale(40)},
  pb44: {paddingBottom: moderateScale(44)},
  pb48: {paddingBottom: moderateScale(48)},
  pb52: {paddingBottom: moderateScale(52)},
  pb56: {paddingBottom: moderateScale(56)},
  pb60: {paddingBottom: moderateScale(60)},

  py0: {paddingVertical: 0},
  py1: {paddingVertical: moderateScale(1)},
  py2: {paddingVertical: moderateScale(2)},
  py3: {paddingVertical: moderateScale(3)},
  py4: {paddingVertical: moderateScale(4)},
  py5: {paddingVertical: moderateScale(5)},
  py6: {paddingVertical: moderateScale(6)},
  py8: {paddingVertical: moderateScale(8)},
  py10: {paddingVertical: moderateScale(10)},
  py12: {paddingVertical: moderateScale(12)},
  py16: {paddingVertical: moderateScale(16)},
  py20: {paddingVertical: moderateScale(20)},
  py24: {paddingVertical: moderateScale(24)},
  py28: {paddingVertical: moderateScale(28)},
  py32: {paddingVertical: moderateScale(32)},
  py36: {paddingVertical: moderateScale(36)},
  py40: {paddingVertical: moderateScale(40)},
  py44: {paddingVertical: moderateScale(44)},
  py48: {paddingVertical: moderateScale(48)},
  py52: {paddingVertical: moderateScale(52)},
  py56: {paddingVertical: moderateScale(56)},
  py60: {paddingVertical: moderateScale(60)},

  px0: {paddingHorizontal: 0},
  px1: {paddingHorizontal: moderateScale(1)},
  px2: {paddingHorizontal: moderateScale(2)},
  px3: {paddingHorizontal: moderateScale(3)},
  px4: {paddingHorizontal: moderateScale(4)},
  px5: {paddingHorizontal: moderateScale(5)},
  px6: {paddingHorizontal: moderateScale(6)},
  px8: {paddingHorizontal: moderateScale(8)},
  px10: {paddingHorizontal: moderateScale(10)},
  px12: {paddingHorizontal: moderateScale(12)},
  px16: {paddingHorizontal: moderateScale(16)},
  px20: {paddingHorizontal: moderateScale(20)},
  px24: {paddingHorizontal: moderateScale(24)},
  px28: {paddingHorizontal: moderateScale(28)},
  px32: {paddingHorizontal: moderateScale(32)},
  px36: {paddingHorizontal: moderateScale(36)},
  px40: {paddingHorizontal: moderateScale(40)},
  px44: {paddingHorizontal: moderateScale(44)},
  px48: {paddingHorizontal: moderateScale(48)},
  px52: {paddingHorizontal: moderateScale(52)},
  px56: {paddingHorizontal: moderateScale(56)},
  px60: {paddingHorizontal: moderateScale(60)},

  p0: {padding: 0},
  p1: {padding: moderateScale(1)},
  p2: {padding: moderateScale(2)},
  p3: {padding: moderateScale(3)},
  p4: {padding: moderateScale(4)},
  p5: {padding: moderateScale(5)},
  p6: {padding: moderateScale(6)},
  p8: {padding: moderateScale(8)},
  p10: {padding: moderateScale(10)},
  p12: {padding: moderateScale(12)},
  p16: {padding: moderateScale(16)},
  p20: {padding: moderateScale(20)},
  p24: {padding: moderateScale(24)},
  p28: {padding: moderateScale(28)},
  p32: {padding: moderateScale(32)},
  p36: {padding: moderateScale(36)},
  p40: {padding: moderateScale(40)},
  p44: {padding: moderateScale(44)},
  p48: {padding: moderateScale(48)},
  p52: {padding: moderateScale(52)},
  p56: {padding: moderateScale(56)},
  p60: {padding: moderateScale(60)},
};

const margin = {
  ml0: {marginLeft: 0},
  ml1: {marginLeft: moderateScale(1)},
  ml2: {marginLeft: moderateScale(2)},
  ml3: {marginLeft: moderateScale(3)},
  ml4: {marginLeft: moderateScale(4)},
  ml5: {marginLeft: moderateScale(5)},
  ml6: {marginLeft: moderateScale(6)},
  ml8: {marginLeft: moderateScale(8)},
  ml10: {marginLeft: moderateScale(10)},
  ml12: {marginLeft: moderateScale(12)},
  ml16: {marginLeft: moderateScale(16)},
  ml20: {marginLeft: moderateScale(20)},
  ml24: {marginLeft: moderateScale(24)},
  ml28: {marginLeft: moderateScale(28)},
  ml32: {marginLeft: moderateScale(32)},
  ml36: {marginLeft: moderateScale(36)},
  ml40: {marginLeft: moderateScale(40)},
  ml44: {marginLeft: moderateScale(44)},
  ml48: {marginLeft: moderateScale(48)},
  ml52: {marginLeft: moderateScale(52)},
  ml56: {marginLeft: moderateScale(56)},
  ml60: {marginLeft: moderateScale(60)},

  mr0: {marginRight: 0},
  mr1: {marginRight: moderateScale(1)},
  mr2: {marginRight: moderateScale(2)},
  mr3: {marginRight: moderateScale(3)},
  mr4: {marginRight: moderateScale(4)},
  mr5: {marginRight: moderateScale(5)},
  mr6: {marginRight: moderateScale(6)},
  mr8: {marginRight: moderateScale(8)},
  mr10: {marginRight: moderateScale(10)},
  mr12: {marginRight: moderateScale(12)},
  mr16: {marginRight: moderateScale(16)},
  mr20: {marginRight: moderateScale(20)},
  mr24: {marginRight: moderateScale(24)},
  mr28: {marginRight: moderateScale(28)},
  mr32: {marginRight: moderateScale(32)},
  mr36: {marginRight: moderateScale(36)},
  mr40: {marginRight: moderateScale(40)},
  mr44: {marginRight: moderateScale(44)},
  mr48: {marginRight: moderateScale(48)},
  mr52: {marginRight: moderateScale(52)},
  mr56: {marginRight: moderateScale(56)},
  mr60: {marginRight: moderateScale(60)},

  mt0: {marginTop: 0},
  mt1: {marginTop: moderateScale(1)},
  mt2: {marginTop: moderateScale(2)},
  mt3: {marginTop: moderateScale(3)},
  mt4: {marginTop: moderateScale(4)},
  mt5: {marginTop: moderateScale(5)},
  mt6: {marginTop: moderateScale(6)},
  mt8: {marginTop: moderateScale(8)},
  mt10: {marginTop: moderateScale(10)},
  mt12: {marginTop: moderateScale(12)},
  mt16: {marginTop: moderateScale(16)},
  mt20: {marginTop: moderateScale(20)},
  mt24: {marginTop: moderateScale(24)},
  mt28: {marginTop: moderateScale(28)},
  mt32: {marginTop: moderateScale(32)},
  mt36: {marginTop: moderateScale(36)},
  mt40: {marginTop: moderateScale(40)},
  mt44: {marginTop: moderateScale(44)},
  mt48: {marginTop: moderateScale(48)},
  mt52: {marginTop: moderateScale(52)},
  mt56: {marginTop: moderateScale(56)},
  mt60: {marginTop: moderateScale(60)},

  mb0: {marginBottom: 0},
  mb1: {marginBottom: moderateScale(1)},
  mb2: {marginBottom: moderateScale(2)},
  mb3: {marginBottom: moderateScale(3)},
  mb4: {marginBottom: moderateScale(4)},
  mb5: {marginBottom: moderateScale(5)},
  mb6: {marginBottom: moderateScale(6)},
  mb8: {marginBottom: moderateScale(8)},
  mb10: {marginBottom: moderateScale(10)},
  mb12: {marginBottom: moderateScale(12)},
  mb16: {marginBottom: moderateScale(16)},
  mb20: {marginBottom: moderateScale(20)},
  mb24: {marginBottom: moderateScale(24)},
  mb28: {marginBottom: moderateScale(28)},
  mb32: {marginBottom: moderateScale(32)},
  mb36: {marginBottom: moderateScale(36)},
  mb40: {marginBottom: moderateScale(40)},
  mb44: {marginBottom: moderateScale(44)},
  mb48: {marginBottom: moderateScale(48)},
  mb52: {marginBottom: moderateScale(52)},
  mb56: {marginBottom: moderateScale(56)},
  mb60: {marginBottom: moderateScale(60)},

  my0: {marginVertical: 0},
  my1: {marginVertical: moderateScale(1)},
  my2: {marginVertical: moderateScale(2)},
  my3: {marginVertical: moderateScale(3)},
  my4: {marginVertical: moderateScale(4)},
  my5: {marginVertical: moderateScale(5)},
  my6: {marginVertical: moderateScale(6)},
  my8: {marginVertical: moderateScale(8)},
  my10: {marginVertical: moderateScale(10)},
  my12: {marginVertical: moderateScale(12)},
  my16: {marginVertical: moderateScale(16)},
  my20: {marginVertical: moderateScale(20)},
  my24: {marginVertical: moderateScale(24)},
  my28: {marginVertical: moderateScale(28)},
  my32: {marginVertical: moderateScale(32)},
  my36: {marginVertical: moderateScale(36)},
  my40: {marginVertical: moderateScale(40)},
  my44: {marginVertical: moderateScale(44)},
  my48: {marginVertical: moderateScale(48)},
  my52: {marginVertical: moderateScale(52)},
  my56: {marginVertical: moderateScale(56)},
  my60: {marginVertical: moderateScale(60)},

  mx0: {marginHorizontal: 0},
  mx1: {marginHorizontal: moderateScale(1)},
  mx2: {marginHorizontal: moderateScale(2)},
  mx3: {marginHorizontal: moderateScale(3)},
  mx4: {marginHorizontal: moderateScale(4)},
  mx5: {marginHorizontal: moderateScale(5)},
  mx6: {marginHorizontal: moderateScale(6)},
  mx8: {marginHorizontal: moderateScale(8)},
  mx10: {marginHorizontal: moderateScale(10)},
  mx12: {marginHorizontal: moderateScale(12)},
  mx16: {marginHorizontal: moderateScale(16)},
  mx20: {marginHorizontal: moderateScale(20)},
  mx24: {marginHorizontal: moderateScale(24)},
  mx28: {marginHorizontal: moderateScale(28)},
  mx32: {marginHorizontal: moderateScale(32)},
  mx36: {marginHorizontal: moderateScale(36)},
  mx40: {marginHorizontal: moderateScale(40)},
  mx44: {marginHorizontal: moderateScale(44)},
  mx48: {marginHorizontal: moderateScale(48)},
  mx52: {marginHorizontal: moderateScale(52)},
  mx56: {marginHorizontal: moderateScale(56)},
  mx60: {marginHorizontal: moderateScale(60)},

  m0: {margin: 0},
  m1: {margin: moderateScale(1)},
  m2: {margin: moderateScale(2)},
  m3: {margin: moderateScale(3)},
  m4: {margin: moderateScale(4)},
  m5: {margin: moderateScale(5)},
  m6: {margin: moderateScale(6)},
  m8: {margin: moderateScale(8)},
  m10: {margin: moderateScale(10)},
  m12: {margin: moderateScale(12)},
  m16: {margin: moderateScale(16)},
  m20: {margin: moderateScale(20)},
  m24: {margin: moderateScale(24)},
  m28: {margin: moderateScale(28)},
  m32: {margin: moderateScale(32)},
  m36: {margin: moderateScale(36)},
  m40: {margin: moderateScale(40)},
  m44: {margin: moderateScale(44)},
  m48: {margin: moderateScale(48)},
  m52: {margin: moderateScale(52)},
  m56: {margin: moderateScale(56)},
  m60: {margin: moderateScale(60)},
};

const position = {
  abs: {position: 'absolute'},
  rel: {position: 'relative'},
  inset0: {top: 0, bottom: 0, right: 0, left: 0},
  insetY0: {top: 0, bottom: 0},
  insetX0: {right: 0, left: 0},
  top0: {top: 0},
  bottom0: {bottom: 0},
  right0: {right: 0},
  left0: {left: 0},
};

const shadow = {
  shadow1: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
  shadow2: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,

    elevation: 4,
  },
  shadow3: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  shadowListItem: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
};

const text = {
  colorPrimary: {color: IS_IOS ? '#3490DC' : '#003737'},
  colorSecondary: {color: '#ff9910'},
  colorTransparent: {color: 'transparent'},
  colorBlack: {color: 'black'},
  colorWhite: {color: 'white'},
  colorGray100: {color: '#f7fafc'},
  colorGray200: {color: '#edf2f7'},
  colorGray300: {color: '#e2e8f0'},
  colorGray400: {color: '#cbd5e0'},
  colorGray500: {color: '#a0aec0'},
  colorGray600: {color: '#718096'},
  colorGray700: {color: '#4a5568'},
  colorGray800: {color: '#2d3748'},
  colorGray900: {color: '#1a202c'},
  colorRed: {color: '#E3342F'},
  colorGreen: {color: '#38C172'},
  colorOrange: {color: '#F6993F'},
  colorYellow: {color: '#FFED4A'},
  colorBlue: {color: '#3490DC'},
  colorTeal: {color: '#4DC0B5'},
  colorIndigo: {color: '#6574CD'},
  colorPurple: {color: '#9561E2'},
  colorPink: {color: '#F66D9B'},
  colorText: {color: '#000'},
  colorIcon: {color: '#000'},
  colorTextMeta: {color: '#8D94A6'},

  textLargeTitle: {
    fontSize: moderateScale(34),
    fontWeight: IS_IOS ? '900' : 'bold',
    lineHeight: moderateScale(41),
  },
  textTitle1: {
    fontSize: moderateScale(28),
    fontWeight: IS_IOS ? '800' : 'bold',
    lineHeight: moderateScale(35),
  },
  textTitle2: {
    fontSize: moderateScale(22),
    fontWeight: IS_IOS ? '800' : 'bold',
    lineHeight: moderateScale(29),
  },
  textTitle3: {
    fontSize: moderateScale(20),
    fontWeight: IS_IOS ? '700' : 'bold',
    lineHeight: moderateScale(27),
  },
  textHeadline: {
    fontSize: moderateScale(17),
    fontWeight: IS_IOS ? '700' : 'bold',
    lineHeight: moderateScale(24),
  },
  textSubheadline: {
    fontSize: moderateScale(16),
    fontWeight: IS_IOS ? '600' : 'bold',
    lineHeight: moderateScale(23),
  },
  textBody: {
    fontSize: moderateScale(15),
    fontWeight: 'normal',
    lineHeight: moderateScale(22),
  },
  textCallout: {
    fontSize: moderateScale(13),
    fontWeight: 'normal',
    lineHeight: moderateScale(19),
  },
  textCaption1: {
    fontSize: moderateScale(12),
    fontWeight: 'normal',
    lineHeight: moderateScale(18),
  },
  textCaption2: {
    fontSize: moderateScale(11),
    fontWeight: 'normal',
    lineHeight: moderateScale(17),
  },
  textBadge: {
    fontSize: moderateScale(9),
    fontWeight: '500',
    lineHeight: moderateScale(15),
  },

  fontBold: {fontWeight: '700'},
  fontMedium: {fontWeight: '600'},
  fontRegular: {fontWeight: '400'},
  fontLight: {fontWeight: '300'},
  textLeft: {textAlign: 'left'},
  textRight: {textAlign: 'right'},
  textCenter: {textAlign: 'center', textAlignVertical: 'center'},
  textJustify: {textAlign: 'justify'},
  textUnderline: {textDecorationLine: 'underline'},
  textThrough: {
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
  },
  textItalic: {fontStyle: 'italic'},
  textBold: {fontWeight: 'bold'},
  textAliVerTop: {textAlignVertical: 'top'},
};

const border = {
  rounded0: {borderRadius: 0},
  rounded1: {borderRadius: moderateScale(7)},
  rounded2: {borderRadius: moderateScale(10)},
  rounded3: {borderRadius: moderateScale(15)},
  rounded4: {borderRadius: moderateScale(20)},
  rounded5: {borderRadius: moderateScale(25)},
  rounded6: {borderRadius: moderateScale(30)},
  rounded7: {borderRadius: moderateScale(35)},
  rounded8: {borderRadius: moderateScale(40)},
  rounded9: {borderRadius: moderateScale(45)},
  rounded10: {borderRadius: moderateScale(50)},

  roundedTopLeft1: {borderTopLeftRadius: moderateScale(7)},
  roundedTopLeft2: {borderTopLeftRadius: moderateScale(10)},
  roundedTopLeft3: {borderTopLeftRadius: moderateScale(15)},
  roundedTopLeft4: {borderTopLeftRadius: moderateScale(20)},
  roundedTopLeft5: {borderTopLeftRadius: moderateScale(25)},
  roundedTopLeft6: {borderTopLeftRadius: moderateScale(30)},
  roundedTopLeft7: {borderTopLeftRadius: moderateScale(35)},
  roundedTopLeft8: {borderTopLeftRadius: moderateScale(40)},
  roundedTopLeft9: {borderTopLeftRadius: moderateScale(45)},
  roundedTopLeft10: {borderTopLeftRadius: moderateScale(50)},

  roundedTopRight1: {borderTopRightRadius: moderateScale(7)},
  roundedTopRight2: {borderTopRightRadius: moderateScale(10)},
  roundedTopRight3: {borderTopRightRadius: moderateScale(15)},
  roundedTopRight4: {borderTopRightRadius: moderateScale(20)},
  roundedTopRight5: {borderTopRightRadius: moderateScale(25)},
  roundedTopRight6: {borderTopRightRadius: moderateScale(30)},
  roundedTopRight7: {borderTopRightRadius: moderateScale(35)},
  roundedTopRight8: {borderTopRightRadius: moderateScale(40)},
  roundedTopRight9: {borderTopRightRadius: moderateScale(45)},
  roundedTopRight10: {borderTopRightRadius: moderateScale(50)},

  roundedBottomLeft1: {borderBottomLeftRadius: moderateScale(7)},
  roundedBottomLeft2: {borderBottomLeftRadius: moderateScale(10)},
  roundedBottomLeft3: {borderBottomLeftRadius: moderateScale(15)},
  roundedBottomLeft4: {borderBottomLeftRadius: moderateScale(20)},
  roundedBottomLeft5: {borderBottomLeftRadius: moderateScale(25)},
  roundedBottomLeft6: {borderBottomLeftRadius: moderateScale(30)},
  roundedBottomLeft7: {borderBottomLeftRadius: moderateScale(35)},
  roundedBottomLeft8: {borderBottomLeftRadius: moderateScale(40)},
  roundedBottomLeft9: {borderBottomLeftRadius: moderateScale(45)},
  roundedBottomLeft10: {borderBottomLeftRadius: moderateScale(50)},

  roundedBottomRight1: {borderBottomRightRadius: moderateScale(7)},
  roundedBottomRight2: {borderBottomRightRadius: moderateScale(10)},
  roundedBottomRight3: {borderBottomRightRadius: moderateScale(15)},
  roundedBottomRight4: {borderBottomRightRadius: moderateScale(20)},
  roundedBottomRight5: {borderBottomRightRadius: moderateScale(25)},
  roundedBottomRight6: {borderBottomRightRadius: moderateScale(30)},
  roundedBottomRight7: {borderBottomRightRadius: moderateScale(35)},
  roundedBottomRight8: {borderBottomRightRadius: moderateScale(40)},
  roundedBottomRight9: {borderBottomRightRadius: moderateScale(45)},
  roundedBottomRight10: {borderBottomRightRadius: moderateScale(50)},

  borderDashed: {borderStyle: 'dashed'},

  borderAll: {
    borderColor: '#EAEAFF',
    borderWidth: 1,
  },
  borderAllDark: {
    borderColor: '#EAEAFF',
    borderWidth: 1,
  },

  borderTop: {
    borderTopColor: '#EAEAFF',
    borderTopWidth: 1,
  },
  borderTopDark: {
    borderTopColor: '#EAEAFF',
    borderTopWidth: 1,
  },

  borderBottom: {
    borderBottomColor: '#EAEAFF',
    borderBottomWidth: 1,
  },
  borderBottomDark: {
    borderBottomColor: '#EAEAFF',
    borderBottomWidth: 1,
  },

  borderRight: {
    borderRightColor: '#EAEAFF',
    borderRightWidth: 1,
  },
  borderRightDark: {
    borderRightColor: '#EAEAFF',
    borderRightWidth: 1,
  },

  borderLeft: {
    borderLeftColor: '#EAEAFF',
    borderLeftWidth: 1,
  },
  borderLeftDark: {
    borderLeftColor: '#EAEAFF',
    borderLeftWidth: 1,
  },
};

export default {
  ...main,
  ...padding,
  ...margin,
  ...position,
  ...shadow,
  ...text,
  ...border,
};
